---
- hosts: Slave
  become: true
  become_user: root
  tasks:
  - name: install tomcat
    yum: name=tomcat state=present
  - name: start tomcat
    service: name=tomcat state=started
  - name: install docker
    yum: name=docker state=present
  - name: start docker
    service: name=docker state=started
  - name: install git
    yum: name=git state=present
  - name: get the dockerfile from githib
    git: repo=https://github.com/swapnil0512/DevOpsClassCodes.git dest=/tmp/gitrepo
  - name: build dockerfile
    command: chdir=/tmp/gitrepo docker build -t projectimage:CICD .
  - name: run the dockerfile
    command: docker run -itd -P projectimage:CICD
  - name: create tag to image
    command: docker tag projectimage:CICD swapnil0512/projectimage:CICD
  - name: loginto docker
    command: docker login --username swapnil0512 --password Swapnil@5
  - name: push image on to dockerhub
    command: docker push swapnil0512/projectimage:CICD
